title: Beechmont Community Orchard
email: hello@bcogrows.org
description: Volunteer-run green space and food orchard in Louisvilleâ€™s Southend.
url: "https://bcogrows.org"
baseurl: ""
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-paginate

sass:
  sass_dir: assets/css
  style: compressed

include:
  - assets

# Pagination only applies to this collection (your blog)
pagination:
  enabled: true
  per_page: 5
  permalink: /page/:num/
  title: ':title (Page :num)'


collections:
  blog:
    output: true
    permalink: /blog/:title/
  events:
    output: true
    permalink: /events/:title/
